addpath matlab;
addpath examples;
run vlfeat/toolbox/vl_setup ;
run matlab/vl_setupnn ;
%{
vl_compilenn('enableGpu', true, ...
'cudaRoot', '/usr/local/cuda-7.5', ...
'cudaMethod', 'nvcc',...
'enableCudnn','true',...
'cudnnroot','local/cudnn-rc4');
%}
warning('off');